Camera
4anotherday/Motor pull request #1
Opened 2021-03-28 15:35 UTC by Antgue01

2021-03-28 21:15 UTC, MiguelZh requested changes

2021-03-28 21:15 UTC, MiguelZh commented on Projects/MotorGrafico/Camera.h
> +	*	@param cameraNum An identifier in case the user wants to create multiple cameras
Cambiamos la manera de comentar al final, mira alguna clase que esté hecha ya y copia el formato (GameObject por ejemplo)

2021-03-28 21:19 UTC, SandraMonLaz commented
Tienes que poner una **constructora por defecto**(y por ende hacer métodos setter para los atributos que no inicialices)

2021-03-31 13:04 UTC, MiguelZh approved these changes

2021-04-06 10:38 UTC, closed without merging